apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: forgejo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusterDecisionResource:
        configMapRef: cluster-appdecision
        labelSelector:
          matchLabels:
            type.app-decisions.example.com: "cluster"
        # Checks for changes every 60sec (default 3min)
        requeueAfterSeconds: 60
  template:
    metadata:
      name: forgejo-{{ .env }}
    spec:
      project: default
      source:
        chart: forgejo
        repoURL: code.forgejo.org/forgejo-helm
        targetRevision: "17.0.1"
        helm:
          releaseName: forgejo
          values: |
            gitea:
              config:
                repository:
                  ENABLE_PUSH_CREATE_USER: true
      destination:
        namespace: forgejo
        server: "{{ .server }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
