apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusterDecisionResource:
        configMapRef: cluster-appdecision
        labelSelector:
          matchLabels:
            type.app-decisions.example.com: "cluster"
        # Checks for changes every 60sec (default 3min)
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "keycloak-{{ .env }}"
    spec:
      destination:
        namespace: keycloak
        server: "{{ .server }}"
      project: default
      source:
        path: apps/keycloak/base
        repoURL: "{{ .repoURL }}"
        targetRevision: "{{ .targetRevision }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
