apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: private-dns
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusterDecisionResource:
        configMapRef: cluster-appdecision
        labelSelector:
          matchLabels:
            type.app-decisions.example.com: "cluster"
        # Checks for changes every 60sec (default 3min)
        requeueAfterSeconds: 60
  template:
    metadata:
      name: private-dns-{{ .env }}
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: default
      source:
        path: apps/private-dns/overlays/{{ .env }}
        repoURL: "{{ .repoURL }}"
        targetRevision: "{{ .targetRevision }}"
      destination:
        namespace: powerdns
        server: "{{ .server }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
