apiVersion: app-decisions.example.com/v1beta1
kind: AppDecision
metadata:
  name: dev
  namespace: argocd
  labels:
    type.app-decisions.example.com: "cluster"
status:
  decisions:
    - repoURL: "http://forgejo-http.forgejo.svc.cluster.local:3000/operations/operations.git"
      targetRevision: HEAD
      server: https://kubernetes.default.svc
      clusterName: in-cluster
      env: dev
