apiVersion: app-decisions.example.com/v1beta1
kind: AppDecision
metadata:
  name: local
  namespace: argocd
  labels:
    type.app-decisions.example.com: "cluster"
status:
  decisions:
    - repoURL: "http://host.minikube.internal:5555"
      targetRevision: HEAD
      server: https://kubernetes.default.svc
      clusterName: in-cluster
      env: local
