apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edp-keycloak-operator
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keycloak-operator
    repoURL: https://epam.github.io/edp-helm-charts/stable
    targetRevision: 1.24.0
    helm:
      values: |
        name: edp-keycloak-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
