apiVersion: kustomize.config.k8s.io/v1alpha1 # <-- Component notation
kind: Component

resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.3/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.3/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.1.3/kubernetes/kubernetes.yml
