apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: keycloak
    unsetOnly: true

components:
  - ../components/keycloak-operator
  - ../components/edp-keycloak-operator
