apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appdecisions.app-decisions.example.com
spec:
  group: app-decisions.example.com
  names:
    kind: AppDecision
    plural: appdecisions
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                decisions:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-appdecision
data:
  apiVersion: app-decisions.example.com/v1beta1
  kind: appdecisions
  statusListKey: decisions
  matchKey: clusterName

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-applicationset-controller-appdecision
rules:
  - apiGroups:
      - app-decisions.example.com
    resources:
      - appdecisions
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-applicationset-controller-appdecision
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-applicationset-controller-appdecision
subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: argocd
