apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: cert-manager
    unsetOnly: true

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
  - issuer.yaml
