apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
spec:
  template:
    spec:
      containers:
      - name: reloader-reloader
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 64Mi